###############################
# Runners + global parts
###############################

include:
  - local: 'ci_cd/GitLab/Common.yml'
  - local: 'ci_cd/GitLab/BuildAndTest_Templates.yml'
  - local: 'ci_cd/GitLab/BuildAndTest_Linux.yml'
  - local: 'ci_cd/GitLab/BuildAndTest_Windows.yml'
  - local: 'ci_cd/GitLab/ConanTemplates.yml'
  - local: 'ci_cd/GitLab/Conan_CreateAndTest_Linux.yml'
  - local: 'ci_cd/GitLab/Conan_CreateAndTest_Windows.yml'
  - local: 'ci_cd/GitLab/Deploy_Conan.yml'
  - local: 'ci_cd/GitLab/Release.yml'
  - local: 'ci_cd/GitLab/SonarCloud.yml'

# GitLab shared new Windows runners
# They currently not support Docker engine
#.windows_runner:
  #tags:
    #- shared-windows
    #- windows
    #- windows-1809

###############################
# API doc
###############################

build_api_doc:
  stage: build
  image: registry.gitlab.com/scandyna/docker-images-ubuntu/ubuntu-18.04-gcc-8:latest
  rules:
    - !reference [.buildAndTest_rules, rules]
  before_script:
    - !reference [.setup_conan, script]
  script:
    - mkdir build
    - cd build
    - conan install
      --profile:build linux_gcc8_x86_64 --profile:host linux_ubuntu-18.04_gcc8_x86_64_qt_widgets_modules
      --settings:build build_type=Release --settings:host build_type=Debug
      --options:host MdtApplication:build_only_doc=True
      ..
    - cmake -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_CPP_API_DOC=ON ..
    - make documentation
  artifacts:
    expire_in: 1 day
    paths:
      - build

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  dependencies:
    - build_api_doc
  script:
    - mv build/doc/html public
  artifacts:
    paths:
      - public
