###############################
# Runners + global parts
###############################

include:
  - local: 'ci_cd/GitLab/Common.yml'
  - local: 'ci_cd/GitLab/Doc.yml'
  #- local: 'ci_cd/GitLab/BuildAndTest_Templates.yml'
  - local: 'ci_cd/GitLab/BuildAndTest_Linux.yml'
  #- local: 'ci_cd/GitLab/BuildAndTest_Windows.yml'
  #- local: 'ci_cd/GitLab/ConanTemplates.yml'
  - local: 'ci_cd/GitLab/Conan_CreateAndTest_Linux.yml'
  #- local: 'ci_cd/GitLab/Conan_CreateAndTest_Windows.yml'
  #- local: 'ci_cd/GitLab/Deploy_Conan.yml'
  #- local: 'ci_cd/GitLab/Release.yml'
  #- local: 'ci_cd/GitLab/SonarCloud.yml'

# GitLab shared new Windows runners
# They currently not support Docker engine
#.windows_runner:
  #tags:
    #- shared-windows
    #- windows
    #- windows-1809
