
default:
  image: registry.gitlab.com/scandyna/docker-images/ubuntu-18.04-cpp-gui:latest


stages:
  - build
  - test
  - deploy


.build_linux:
  stage: build
  before_script:
    - conan config install --source-folder conan https://gitlab.com/scandyna/conan-config.git
    - conan remote update scandyna https://api.bintray.com/conan/scandyna/public-conan --insert 0 # Check for package in scandyna first
  script:
    - mkdir build
    - cd build
    - conan install --profile $CONAN_PROFILE -s build_type=$BUILD_TYPE -o build_tests=True -o MdtApplication:gui=False ..
    - cmake -G"Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNING_AS_ERROR=ON
                               -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER $CMAKE_EXTRA_CACHE_ENTRIES
                               -DBUILD_SHARED_LIBS=ON -DBUILD_USE_IPO_LTO=ON
                               -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
                               -DENABLE_CORE_APPLICATION_FOR_NON_QT_USAGE=ON
                               -DENABLE_GUI_APPLICATION_FOR_NON_QT_USAGE=OFF
                               ..
    - make -j4
  artifacts:
    expire_in: 1 day
    paths:
      - build


.test_linux:
  stage: test
  script:
    - cd build
    - ctest --output-on-failure .


build_linux_gcc7_x86_64_debug:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    C_COMPILER: gcc-7
    CXX_COMPILER: g++-7
    BUILD_TYPE: Debug
  extends: .build_linux

test_linux_gcc7_x86_64_debug:
  dependencies:
    - build_linux_gcc7_x86_64_debug
  extends: .test_linux
